print("      ////")
print("     |*****|")
print("     | $ $ |")
print("     |  0  |")
print("     *******")
print("       ***")
print("  **************")
print(" *  *    *   *   *")
print("*  *     *     *    *")
print("  *  *   *      *  * ")
print( "    *  **   *  *")
print("     *   *      * ")
print("     ************")
print("        $$$ $$$")
print("        $$$ $$$")
print("        $$$ $$$")
print("        $$$ $$$")
print("        $$$ $$$")
print("       9999 9999")